/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
              "primary-container": "#7c3aed",
              "on-surface": "#e8dfee",
              "secondary": "#43e5b1",
              "on-surface-variant": "#ccc3d8",
              "on-primary": "#3f008e",
              "secondary-fixed": "#60fcc6",
              "inverse-on-surface": "#332f39",
              "secondary-container": "#01c896",
              "on-primary-fixed-variant": "#5a00c6",
              "on-secondary": "#003828",
              "inverse-primary": "#732ee4",
              "background": "#15121b",
              "on-tertiary-fixed-variant": "#85145a",
              "on-error": "#690005",
              "primary": "#d2bbff",
              "on-primary-container": "#ede0ff",
              "inverse-surface": "#e8dfee",
              "surface-container-lowest": "#100d16",
              "on-background": "#e8dfee",
              "tertiary-fixed": "#ffd8e7",
              "tertiary": "#ffafd3",
              "on-tertiary-fixed": "#3d0026",
              "error-container": "#93000a",
              "on-tertiary-container": "#ffdce9",
              "on-error-container": "#ffdad6",
              "on-secondary-fixed-variant": "#00513b",
              "outline": "#958da1",
              "surface-container": "#221e28",
              "on-primary-fixed": "#25005a",
              "primary-fixed-dim": "#d2bbff",
              "secondary-fixed-dim": "#3adfab",
              "surface-variant": "#37333e",
              "surface-bright": "#3c3742",
              "surface-container-highest": "#37333e",
              "surface-container-high": "#2c2833",
              "on-tertiary": "#620040",
              "surface-tint": "#d2bbff",
              "tertiary-fixed-dim": "#ffafd3",
              "tertiary-container": "#ae397b",
              "primary-fixed": "#eaddff",
              "on-secondary-container": "#004d38",
              "surface-dim": "#15121b",
              "surface": "#15121b",
              "on-secondary-fixed": "#002116",
              "outline-variant": "#4a4455",
              "surface-container-low": "#1d1a24",
              "error": "#ffb4ab"
      },
      "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
      },
      "spacing": {
              "base": "4px",
              "gutter": "24px",
              "sm": "16px",
              "md": "24px",
              "lg": "48px",
              "xl": "80px",
              "xs": "8px",
              "container-max": "1280px"
      },
      "fontFamily": {
              "label-md": ["Inter"],
              "body-lg": ["Inter"],
              "display": ["Sora"],
              "h2": ["Sora"],
              "h1-mobile": ["Sora"],
              "h3": ["Sora"],
              "body-md": ["Inter"],
              "h1": ["Sora"]
      },
      "fontSize": {
              "label-md": ["0.875rem", {"lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600"}],
              "body-lg": ["1.125rem", {"lineHeight": "1.6", "fontWeight": "400"}],
              "display": ["4.5rem", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "800"}],
              "h2": ["2.25rem", {"lineHeight": "1.3", "fontWeight": "700"}],
              "h1-mobile": ["2.25rem", {"lineHeight": "1.2", "fontWeight": "800"}],
              "h3": ["1.5rem", {"lineHeight": "1.4", "fontWeight": "600"}],
              "body-md": ["1rem", {"lineHeight": "1.5", "fontWeight": "400"}],
              "h1": ["3rem", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "800"}]
      }
    },
  },
  plugins: [],
}
